name: first_workflow
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print OS info
        run: cat /etc/os-release
      - name: Print goodbye
        run: echo "Done - bye"
